# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional license services. Since it's optional, this file is
# dependent of docker-compose file from <project_root>/docker. In order to run this services, execute command:
# docker-compose -f docker/docker-compose.yml -f docker/addons/license/docker-compose.yml up
# from project root.

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

volumes:
  mainflux-license-db-volume:

services:
  license-db:
    image: postgres:12.1-alpine
    container_name: mainflux-license-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${MF_LICENSE_DB_USER}
      POSTGRES_PASSWORD: ${MF_LICENSE_DB_PASS}
      POSTGRES_DB: ${MF_LICENSE_DB}
    networks:
      - docker_mainflux-base-net
    volumes:
      - mainflux-license-db-volume:/var/lib/postgresql/data

  license:
    image: mainflux/license-service:latest
    container_name: mainflux-license
    depends_on:
      - license-db
    restart: on-failure
    ports:
      - ${MF_LICENSE_PORT}:${MF_LICENSE_PORT}
    environment:
      MF_LICENSE_LOG_LEVEL: ${MF_LICENSE_LOG_LEVEL}
      MF_LICENSE_DB_HOST: license-db
      MF_LICENSE_DB_PORT: ${MF_LICENSE_DB_PORT}
      MF_LICENSE_DB_USER: ${MF_LICENSE_DB_USER}
      MF_LICENSE_DB_PASS: ${MF_LICENSE_DB_PASS}
      MF_LICENSE_DB: ${MF_LICENSE_DB}
      MF_LICENSE_DB_SSL_MODE: ${MF_LICENSE_DB_SSL_MODE}
      MF_LICENSE_PORT: ${MF_LICENSE_PORT}
      MF_AUTH_URL: authn:${MF_AUTHN_GRPC_PORT}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
    networks:
      - docker_mainflux-base-net
